#!/usr/bin/env python3
"""Convert web assets into a C++ header with embedded string literals."""

import sys
from pathlib import Path


def escape_for_raw(content: str) -> str:
    """Wrap content in a C++ raw string literal, handling edge cases."""
    # Find a delimiter that doesn't appear in the content
    delim = "XPRV"
    while f"){delim}\"" in content:
        delim += "X"
    return f'R"{delim}({content}){delim}"'


def main() -> None:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output.h> <file1> [file2 ...]", file=sys.stderr)
        sys.exit(1)

    output = Path(sys.argv[1])
    files = [Path(f) for f in sys.argv[2:]]

    lines = [
        "#pragma once",
        "// Auto-generated by embed.py — do not edit",
        "#include <string_view>",
        "",
        "namespace xprv::web {",
        "",
    ]

    for f in files:
        content = f.read_text()
        name = f.stem.replace("-", "_").replace(".", "_")
        raw = escape_for_raw(content)
        lines.append(f"inline constexpr std::string_view {name} = {raw};")
        lines.append("")

    lines.append("}  // namespace xprv::web")
    lines.append("")

    output.write_text("\n".join(lines))
    print(f"Embedded {len(files)} file(s) → {output}")


if __name__ == "__main__":
    main()
