#!/usr/bin/env python3
"""Generate compile-time field-code constants common to XRPL and Xahau.

A field is emitted only if it is defined in BOTH network definition files AND
has an identical field code ((type << 16) | nth) in each. Such a constant is
therefore safe to compare against FieldDef::code regardless of which network's
protocol is loaded — letting visitors do integer code comparison instead of
brittle, slow string matching on field names.

Fields that differ in code between the networks (e.g. HookOn, the high-level
pseudo-types), or whose names are not valid C++ identifiers, are excluded and
listed in the generated header's banner comment.

Usage:
  generate-known-fields.py <xahau.json> <xrpl.json> <output.h>
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def load(path: str) -> dict[str, tuple[int, str, int]]:
    doc = json.loads(Path(path).read_text())
    if "FIELDS" not in doc and isinstance(doc.get("result"), dict):
        doc = doc["result"]
    types = dict(doc["TYPES"])
    out: dict[str, tuple[int, str, int]] = {}
    for name, info in doc["FIELDS"]:
        tc = types.get(info["type"])
        if tc is None:
            continue
        # Only real wire fields: skip non-serialized pseudo-fields (Generic,
        # Invalid, hash, index) — some carry negative special type codes and
        # never appear in serialized data, so a constant for them is useless.
        if not info.get("isSerialized", False):
            continue
        # Belt-and-suspenders: serializable types occupy codes 1..9999; the
        # high-level pseudo-types (Transaction=10001, ...) and the specials
        # (Unknown=-2, Done=65535) are not wire field types.
        if not (1 <= int(tc) < 10000):
            continue
        out[name] = ((int(tc) << 16) | int(info["nth"]), info["type"], int(info["nth"]))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("xahau")
    ap.add_argument("xrpl")
    ap.add_argument("output")
    args = ap.parse_args()

    xah = load(args.xahau)
    xrpl = load(args.xrpl)

    common = sorted(set(xah) & set(xrpl))
    emit: list[tuple[str, int, str, int]] = []
    conflicts: list[str] = []
    non_ident: list[str] = []
    for name in common:
        if xah[name][0] != xrpl[name][0]:
            conflicts.append(name)
            continue
        if not IDENT.match(name):
            non_ident.append(name)
            continue
        code, typ, nth = xah[name]
        emit.append((name, code, typ, nth))
    emit.sort(key=lambda e: e[1])  # deterministic: by field code

    L: list[str] = []
    L.append("// AUTO-GENERATED by scripts/generate-known-fields.py — DO NOT EDIT.")
    L.append("//")
    L.append("// Field-code constants for fields common to BOTH XRPL and Xahau with an")
    L.append("// identical code, so they are safe to compare against FieldDef::code no")
    L.append("// matter which network's protocol is loaded. Prefer these over matching on")
    L.append("// FieldDef::name strings (faster, typo-proof).")
    L.append("//")
    L.append(f"//   xahau: {Path(args.xahau).name}")
    L.append(f"//   xrpl:  {Path(args.xrpl).name}")
    L.append(f"//   emitted: {len(emit)} common same-code fields")
    if conflicts:
        L.append(f"//   excluded (code differs between networks): {', '.join(conflicts)}")
    if non_ident:
        L.append(f"//   excluded (not a C++ identifier): {', '.join(non_ident)}")
    L.append("")
    L.append("#pragma once")
    L.append("")
    L.append("#include <cstdint>")
    L.append("")
    L.append("namespace catl::xdata::sf {")
    L.append("")
    for name, code, typ, nth in emit:
        L.append(f"inline constexpr std::uint32_t {name} = 0x{code:05X}u;  // {typ} nth={nth}")
    L.append("")
    L.append("// All emitted constants as a table, for iteration / cross-checking against")
    L.append("// a loaded Protocol (see known-fields-gtest).")
    L.append("struct KnownField")
    L.append("{")
    L.append("    char const* name;")
    L.append("    std::uint32_t code;")
    L.append("};")
    L.append("")
    L.append("inline constexpr KnownField kAll[] = {")
    for name, code, typ, nth in emit:
        L.append(f"    {{\"{name}\", {name}}},")
    L.append("};")
    L.append("")
    L.append("}  // namespace catl::xdata::sf")
    Path(args.output).write_text("\n".join(L) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
