name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04  # Use Ubuntu 24.04 which has GCC 14 by default
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
        generator: [Ninja, Makefiles]
        include:
          - compiler: gcc
            cc: gcc-13
            cxx: g++-13
            version: 13
          - compiler: clang
            cc: clang-16
            cxx: clang++-16
            version: 16
    env:
      build_dir: build
      CACHE_VERSION: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          
          # GCC 14 is already available on Ubuntu 24.04
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y build-essential libstdc++-14-dev
          fi
          
          # For Clang, install with libc++ support
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y clang-16 libc++-dev libc++abi-dev
          fi

          # Log clang and gcc versions
          echo "Running ${{ matrix.cc }} --version"
          ${{ matrix.cc }} --version
          echo "Running ${{ matrix.cxx }} --version"
          ${{ matrix.cxx }} --version

          # Install specific Conan version needed
          pip install --upgrade conan

      - name: Verify compiler versions
        run: |
          ${{ matrix.cc }} --version
          ${{ matrix.cxx }} --version

      - name: Restore Conan cache
        id: cache-restore-conan
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.conan2
          key: ${{ runner.os }}-conan-${{env.CACHE_VERSION}}=${{ matrix.compiler }}-${{ matrix.build_type }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-conan-${{env.CACHE_VERSION}}-${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Configure Conan
        run: |
          conan profile detect --name detected --force
          mkdir -p "$(conan config home)/profiles"
          cat >$(conan config home)/profiles/default <<EOF
          include(detected)
          [settings]
          compiler.cppstd=20
          compiler.libcxx=libstdc++
          build_type=${{ matrix.build_type }}
          [conf]
          tools.build:compiler_executables={"c": "/usr/bin/${{ matrix.cc }}", "cpp": "/usr/bin/${{ matrix.cxx }}"}
          EOF
          echo "Detected conan profile:"
          conan profile show -pr detected
          echo "Default conan profile:"
          conan profile show -pr default

      - name: Install dependencies
        id: conan-install
        run: |
          mkdir -p ${{ env.build_dir }}
          cd ${{ env.build_dir }}
          conan install \
            --output-folder . \
            --build missing \
            --settings build_type=${{ matrix.build_type }} \
            ..
        continue-on-error: true

      - name: Save Conan cache
        if: steps.cache-restore-conan.outputs.cache-hit != 'true' && steps.conan-install.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.conan2
          key: ${{ runner.os }}-conan-${{env.CACHE_VERSION}}-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}

      - name: Configure CMake
        run: |
          cd ${{ env.build_dir }}
          if [ "${{ matrix.generator }}" = "Ninja" ]; then
            cmake -G "Ninja" \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.cc }} \
              -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.cxx }} \
              -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
              ..
          else
            cmake -G "Unix Makefiles" \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.cc }} \
              -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.cxx }} \
              -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
              ..
          fi

      - name: Build
        run: |
          cd ${{ env.build_dir }}
          if [ "${{ matrix.generator }}" = "Ninja" ]; then
            ninja
          else
            make -j$(nproc)
          fi

      - name: Run tests
        run: |
          cd ${{ env.build_dir }}
          # Check if all_tests exists and run it
          if [ -f "bin/all_tests" ]; then
            echo "Running all_tests"
            ./bin/all_tests
          elif [ -f "tests/all_tests" ]; then
            echo "Running all_tests from tests directory"
            ./tests/all_tests  
          elif [ -f "all_tests" ]; then
            echo "Running all_tests from build root"
            ./all_tests
          else
            echo "Error: all_tests executable not found in expected locations"
            find . -name "all_tests" -type f
            exit 1
          fi